### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by alamaison** [rji/jenkins-standalone#1]
Thanks for the script ... and the blog.  Is there an open-source licence for this repo?

**Comment by rji** [comment]
Hey @alamaison, thanks for checking it out! I've pushed up a LICENSE file to the root of the repo. In short, this work is in the public domain. Feel free to do with it what you will. If you'd like to attribute the original work to me, great! If not, no worries.

It's really there for the open source community to try out running Jenkins masters on Mesos. There will likely need to be modifications to the script, the configurations, etc for individual environments that I haven't considered, so happy hacking :)

**Comment by alamaison** [comment]
Thanks!
